[package]
name = "ring_io"
version = "0.1.0"
authors = ["Sherlock Holo <sherlockya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-io = "0.3"
futures-util = "0.3"
libc = "0.2"
once_cell = "1.3"
iou = "0.0.0-ringbahn.1"
slab = "0.4"
bytes = "0.5"
uring-sys = "0.6"

[dev-dependencies]
tempfile = "3.1"
futures-executor = "0.3"
futures-util = { version = "0.3", features = ["io"] }
