[package]
name = "ring_io"
version = "0.2.0"
authors = ["Sherlock Holo <sherlockya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-io = "0.3"
futures-util = { version = "0.3", default-features = false }
io-uring = { version = "0.5", features = ["unstable"] }
nix = "0.22"
libc = "0.2"
slab = "0.4"
async-task = "4.0"
crossbeam-channel = "0.5"

[dev-dependencies]
futures-util = { version = "0.3", features = ["io", "bilock", "unstable"], default-features = false }
tempfile = "3.2"
futures-timer = "3.0"
