[package]
name = "ring_io"
version = "0.1.0"
authors = ["Sherlock Holo <sherlockya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
io-uring = { version = "0.3", features = ["concurrent"] }
futures-channel = "0.3"
futures-util = "0.3"
libc = "0.2"
once_cell = "1.3"

[dev-dependencies]
tempfile = "3.1"
futures-executor = "0.3"
